sudo: required
services:
  - docker

before_install:
  - docker build -t shaydeecoder/docker-next -f Dockerfile.dev .

script:
  - docker run -e CI=true shaydeecoder/docker-next npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-next"
  env: "Docker-next-env"
  bucket_name: "elasticbeanstalk-us-east-1-120036518459"
  bucket_path: "docker-next"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
