name: CI and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t shaydeecoder/docker-next -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true shaydeecoder/docker-next npm run test:ci

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: us-east-1

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r deploy.zip . -x ".git/*"
          aws s3 cp deploy.zip s3://elasticbeanstalk-us-east-1-120036518459/docker-next/
          aws elasticbeanstalk create-application-version \
            --application-name docker-next \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-120036518459",S3Key="docker-next/deploy.zip"
          aws elasticbeanstalk update-environment \
            --environment-name Docker-next-env \
            --version-label $GITHUB_SHA
